### PR TITLE
Create modules/rpc/auth.c

### PR DESCRIPTION
**Pull request by ValwareIRC**
Login and Logout users on IRC over RPC. Likely to be useful at some point.

### CODE REVIEW

**Comment by ValwareIRC** [comment]
I'll redo this tomorrow...

**Comment by TinCanTech** [comment]
Forgive until next Tuesday.

**Comment by ValwareIRC** [comment]
> Forgive until next Tuesday.

Sorry? What's this about?

**Comment by TinCanTech** [comment]
I saw you were having some trouble; My comment is meant only as friendly support. Please disregard it.

**Comment by ValwareIRC** [comment]
ohhh I didn't understand it at all, not even context XD now I understand! Thank you for your support!

**Comment by ValwareIRC** [comment]
I've reopened them properly now =]

**Pull request closed without merging**
