### PR TITLE
Add strip ANSI color codes ability in StripColors function. (#4101)

### PR DESCRIPTION
**Pull request by dboyz**
Code is not extensively tested. Variables nc, col, rgb and ans should be
an integer here.

### CODE REVIEW

**Comment by dboyz** [comment]
I referred to @grawity's irc-docs for ansi color code formats https://github.com/grawity/irc-docs/blob/b98b4bb4a36cba18a5440657d69027580af56ba5/client/epic5-colors2.txt

**Comment by grawity** [comment]
I'm trying to understand what |nc| does here. Does it limit the number of `;` components or something?

(Actual color codes might have any number, from `\e[m` to `\e[;;;;m` to `\e[1;3;4;7;37m` to `\e[38;2;165;127;119m` to perhaps not-very-valid `\e[1;3;4;7;38;2;165;127;119;48;2;65;27;119m`...)

**Comment by dboyz** [comment]
@grawity `nc` counts the number of characters after a color code is found. If special characters are found like `,` in normal color, `;` and `m`  in ansi color, the count resets to 0.

This code should work fine on your examples since `nc` is resetted each time when special character `;` is found and only stops *stripping* after special character `m` is found.

**Comment by tmcarthur** [comment]
Will pull into my local branch and have a look - thanks.

**Comment by dboyz** [comment]
Thanks! :)

**Comment by syzop** [comment]
bump ;)

**Comment by dboyz** [comment]
Revisiting my PR. Should we strip bold, italics and underline codes too in this function?

**Pull request closed without merging**
