### PR TITLE
help: Change numerics for consistency with other IRCds

### PR DESCRIPTION
**Pull request by progval**
This is GH-167, rebased on unreal60_dev.

Screenshots below, with the two versions (first the current one, then the one I'm proposing)

# Looks much better

Konversation:

konversation_1.8-20121

KVIrc
kvirc_5 0 0

# Looks the same

IRCCloud:

irccloud

Srain:

srain_1.2.4

# Looks slightly worse, as the client shows the command name (here, it's `*`) before the text

Gamja:

gamja

Hexchat:

hexchat_2.14.3

irssi:

irssi_1.3

KiwiIRC:

kiwiirc

Quassel:

quassel_0.13.1

Weechat:

weechat_3.0

### CODE REVIEW

**Comment by syzop** [comment]
I see this is lingering again, better to make a decision than no decision:
I find it rather ugly for those cases where it looks worse... especially since you only used `*` as a command and for something like `CHMODES` etc or any other query it would look a lot more worse... repeating that command over in over, prefixed everywhere, not nice at those clients. And... there are only two clients at which it looks better.

I am going to do what I have often done with numeric changes in the past 20 years: I am going to wait with this until clients catch up and show things more nicely. In the meantime, I don't think I should keep this PR open for the next 2 years while waiting for such a moment, that would look silly, so I am closing it. I hope you keep going on with your improvements and let's see in 2 years or so if things have evolved for the better.

**Comment by progval** [comment]
If you don't mind, I'll use this PR to keep track of the progress of adding support to clients.

The Lounge already supports the new numerics better:

screenshot-2022-04-01_14-57-24

For the other clients mentioned above that need to be improved:

* https://github.com/kiwiirc/kiwiirc/pull/1509
* https://github.com/irssi/irssi/pull/1371
* https://github.com/weechat/weechat/pull/1772
* https://github.com/quassel/quassel/pull/601

**Comment by syzop** [comment]
> If you don't mind, I'll use this PR to keep track of the progress of adding support to clients.

Yes, no problem :)

**Comment by progval** [comment]
Four major clients (KiwiIRC, irssi, weechat, and Quassel) merged my PRs to add support for the new numerics. This leaves only Hexchat (which is abandonware) and Gamja. Is it good enough to merge this PR now?

**Pull request closed without merging**
