### PR TITLE
Correcting a tenacious typo. s/succesfully/successfully/g

### PR DESCRIPTION
**Pull request by theRoda**
I am writing grok filters for unreal logs and having to intentionally type this typo is figuratively killing me.

### CODE REVIEW

**Comment by syzop** [comment]
Will look into this after 4.0.0 freeze. Thanks.

**Comment by dboyz** [comment]
Bump. @theRoda there are some conflicts in your branch if you are still interested with this PR.

**Comment by cehib** [comment]
Why were there so many spelling errors in the first instance and what's there to "look at", this just fixes them, no?

**Comment by syzop** [comment]
Didn't know anyone could get so upset about a spelling error :D.

Anyway, this PR has been superseded by another one from GLolol who did the necessary updates, allowing us to actually merge the changes. You were credited as well in the commit 64839a6304230d01856f347a2589b58f7d711956.

**Pull request closed without merging**
