### PR TITLE
restrict-commands: add option 'channel-create' (channel creation)

### PR DESCRIPTION
**Pull request by ValwareIRC**
This has been a commonly requested feature with different requested options, I think it makes sense to do it properly from here

### CODE REVIEW

**Comment by d3xt3r01** [comment]
+1 LGTM!

**Comment by syzop** [comment]
I think this would be nice enhancement, people have asked for it before.
Had some initial doubts on whether it should be in set::restrict-commands but... having it there has the benefit of the delay stuff and re-using the same functionality that is used for other things there. I guess we can put it there.

Some notes on the patch:

I see that unrelated parts of the file got re-indented (the whitespace changes), from good aligned arguments on the second line to a semi-random amount of tabs it seems :D. If you can undo those changes...

I also see you have a `sub1_from_channel()` but in the can_join hook you should just return error (as you already do). In `can_join` in the core code (src/modules/join.c) there is no sub1_from_channel for other cases either, which implies this should not be done.

**Comment by ValwareIRC** [comment]
I only sub1_from_channel() as a quick way to clean up the channel which, without it, would still exist in the LIST output with 0 users, and also be unjoinable.

**Comment by syzop** [comment]
Ok, then that is an indication our code is wrong. Fixed now in https://github.com/unrealircd/unrealircd/commit/33c6eb0bcf6a10b3a62270214528cda41347577b. Thanks!

**Comment by ValwareIRC** [comment]
And fixed! =]

**Pull request merged**
