### PR TITLE
Added server count to the local server notice for /rehash -global

### PR DESCRIPTION
**Pull request by GottemHams**
In regards to my [bug report](https://bugs.unrealircd.org/view.php?id=4739) I figured I may as well give it a shot myself.

### CODE REVIEW

**Comment by bonnedav** [comment]
Why has this not been merged yet?

**Comment by syzop** [comment]
If this would be changed to be a single patch that only does what https://bugs.unrealircd.org/view.php?id=4739 suggested then it can be merged (if it's good). Right now it consists of 3 patches with more unrelated than related changes :D
Actually I'm just going to close it, best to resubmit I think.

**Comment by GottemHams** [comment]
Yeahhhhhh I think I made this pull request before I even wrote my first module, so. :D I'll redo it sometime. Also not to mention I set up my Sublime Text to strip trailing whitespace.

**Comment by GottemHams** [comment]
Better yet, I'm going to let go of this "patch" entirely. :D I had to add a custom rehash -flag due to a certain module I'm using on our network and I simply added the functionality in there. =]

**Pull request closed without merging**
